### ISSUE TITLE
Error: TagBot experienced an unexpected internal failure

### ISSUE THREAD

**Issue by baxmittens** [JuliaRegistries/General#101330]
I am failing to register a new version of my package

https://github.com/baxmittens/VTUFileHandler.jl

```
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/local/lib/python3.8/site-packages/toml/decoder.py", line 781, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!
```

Can somebody tell me what I am doing wrong? I am using a standard version of the TagBot. What do duplicate keys mean?
Thank you

**Comment by baxmittens** [comment]
The error
````
ValueError("Duplicate keys!")
```
referred to the `Project.toml` in my case. There was a duplicate compat entry.
